name: GitHub Action Demo

on:
    push:
        branches:
            - main

jobs:
    build:
        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest]
        runs-on: ${{ matrix.os }}
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4
          - name: Set up Node.js
            uses: actions/setup-node@v4
            with:
                node-version: 18.x
          - name: Install dependencies
            run: npm install
          - name: Install xvfb
            if: runner.os == 'Linux'
            run: sudo apt-get -y install xvfb
          - name: Run tests on Linux OS
            if: runner.os == 'Linux'
            run: xvfb-run -a npm test
          - name: Run tests on a non-Linux OS
            if: runner.os != 'Linux'
            run: npm test
